GrowingPetPlant/Back

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/user/controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/user/domain/User.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/user/service/UserService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/user/service/port/UserRepository.java, GrowingPetPlant/src/main/resources/application-mysql.properties
=> [FEAT/#1] 로그인

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/user/controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/user/dto/GetLoginReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/user/service/UserService.java
=> [KSJ/FIX]로그인 - RequestBody 수정

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/DTO/GetFindUserIdReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/DTO/GetFindUserPwdReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/Port/UserRepository.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
아이디 및 비밀번호 찾기 api
아이디 찾기 
이름, 전화번호 -> 000 사용자의 아이디는 [000]입니다. / 존재하지 않는 사용자입니다.
비밀번호 찾기 
아이디, 이름, 전화번호 -> 000 사용자의 비밀번호는 [000]입니다. / 존재하지 않는 사용자입니다.
=> [KSJ/FEAT#4]아이디/비밀번호 찾기

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/DTO/GetFindUserPwdReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
비밀번호 찾기 api 수정
기존 : 아이디, 유저명, 핸드폰 번호 -> 비밀번호
변경 : 아이디, 유저명 -> 비밀번호
=> [KSJ/MOD]비밀번호 찾기 수정

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
=> [yjs/delete] delete

GrowingPetPlant/build.gradle, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Controller/ArduinoController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Service/ArduinoService.java
ArduinoController, ArduinoService Update.
=> [KSJ/FEAT#9]아두이노 연결부 - 테스트

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/DTO/PutLoginReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
- login GetMapping -> PostMapping
=> [yjs/fix] login fix

GrowingPetPlant/build.gradle, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Controller/ArduinoController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/DTO/PostWateringReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Service/ArduinoService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/GrowingPetPlantApplication.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Status.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/StatusController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/StatusRepository.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/StatusService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Subscribe/Subscriber.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/DTO/PostLoginReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
1. Mqtt - Publish : DB update
2. Springboot - Publish : Watering
3. 홈 화면 상태바 디스플레이 api 3개
4. Subscriber.java : DB url, username, password 변수화
=> [KSJ/FEAT#12]MQTT-Server, Status Display, Watering

GrowingPetPlant/build.gradle, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Service/ArduinoService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Exception/ApiExceptionHandler.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Controller/StatusController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Domain/Status.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Service/Port/StatusRepository.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Service/StatusService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Domain/User.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/UserPlant/Domain/UserPlant.java
아이디
-공백X, 3-10자리, 영문 소문자 필수, 영문 대소문자, 숫자 허용
비밀번호
-공백X, 8-16자리, 영문 소문자, 숫자, 특수문자 필수, 영문 대소문자, 숫자, 특수문자 허용
이름
-공백X
전화번호
-XXX-XXXX-XXXX 형식
식물 이름
-공백X
식물 타입 
-공백X
=> [KSJ/FEAT#14]회원가입 유효성 검사

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Exception/ApiExceptionHandler.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Domain/User.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
로그인 성공 -> 유저 아이디 리턴
로그인 실패 -> 로그인에 실패했습니다 리턴
=> [KSJ/FEAT#16 login id return

GrowingPetPlant/.gitignore, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/GrowingPetPlantApplication.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Controller/StatusController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Service/Port/StatusRepository.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Service/StatusService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/UserPlant/Controller/UserPlantController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/UserPlant/Service/UserPlantService.java
Status
식물에 물 준 날짜 리턴 api 생성
gitignore
application-mqtt.properties 추가(보완 필요)
=> [KSJ/FEAT#17 물 준 날짜 리턴, gitignore 수정

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Controller/StatusController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Service/Port/StatusRepository.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Service/StatusService.java
상태바 디스플레이 api 수정
Status 데이터베이스에서 plantNumber와 일치하는 데이터 중 가장 최근 Status 찾기
-> 최근 온도
-> 최근 습도
-> 최근 토양 습도
=> [KSJ/MOD]상태바 디스플레이 api update

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Controller/ArduinoController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Service/ArduinoService.java
물 주기 버튼 클릭 
-> if, 오늘 물을 주었을 경우
-> 오늘 이미 물을 주셨습니다. 물을 주시겠습니까?
-> else
-> 물을 주시겠습니까?
팝업창 확인 클릭
-> 물 주기 api
=> [KSJ/FEAT#19] 물 주기 버튼 클릭, 물 주기

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Controller/ArduinoController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Service/ArduinoService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/DTO/PostStatusReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Service/Port/StatusRepository.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Service/StatusService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/Port/UserRepository.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
로그인 api 
- 성공 : 유저 번호 리턴
- 실패 : null 리턴
아이디 -> 유저 찾기 --> 유저 번호 -> 유저 찾기
-성공 : 유저 정보 리턴
- 실패 : null 리턴
=> [KSJ/MOD]로그인 api 및 유저 번호로 유저 찾기 api 수정

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/DTO/PostLoginRes.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/DTO/PostSignupReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Domain/User.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
1. 비밀번호 암호화 적용
- PasswordEncoder 활용해 encode로 암호화해 DB에 저장 및 matchers로 비밀번호 일치 확인.
2. 회원가입 유효성 검사 수정
- 비밀번호 암호화를 적용하니 회원가입 유효성 검사가 제대로 동작하지 않음을 발견했다.
Why? 비밀번호 암호화가 적용된 후 회원가입 유효성 검사가 적용되었기 때문에!
Controller가 아닌 PostSignUpReq에서 @Valid 적용을 통해 회원가입 유효성 검사를 먼저 진행해준 후 비밀번호 암호화를 진행했다.
3. 리턴 값 수정
- 로그인 api의 리턴 값이 케이스마다 다르게 텍스트를 리턴하게 작성하고 싶었다.
- PostLoginRes를 생성해 message, token 정보를 같이 리턴해줬다.
=> 비밀번호 암호화 적용 및 회원가입 유효성 수정

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Service/ArduinoService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Plant/Domain/Plant.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Domain/User.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/Port/UserRepository.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
온실 자동화 로직 구현
- User DB 수정
- auto, notification 속성 추가
- Plant DB 수정 및 정보 추가
- high_temp, low_temp, opt_moisture 속성 추가
- 토마토, 오이, 바질, 당근, 고추 데이터 추가
- 실행 시간 단위 설정(1일마다)
- 최근 상태 불러와 최적 상태 유지 로직 실행
- 최고 온도, 최적 대기 습도보다 높고, 팬 OFF인 경우 -> 팬 작동
- 최저 온도, 최적 대기 습도보다 낮고, 팬 ON인 경우 -> 팬 끄기
- 최적 토양 습도보다 낮은 경우 -> 수분 공급
=> 온실 자동화 로직 구현

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/UserPlant/Controller/UserPlantController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/UserPlant/DTO/PatchChangeUserPlantNameReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/UserPlant/Service/UserPlantService.java
유저 식물 이름 변경 API 구현
PatchChangeUserPlantNameReq로 유저 식물 번호, 변경할 유저 식물 이름을 받아 API를 구성했습니다.
=> 유저 식물 이름 변경 API 구현

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Plant/PlantRepository.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/DTO/GetHomeInfoRes.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/UserPlant/Controller/UserPlantController.java
식물 정보 추가 API
- 성공시 상태 코드 OK로 리턴하게 수정
홈 화면 정보 API
- 식물 종도 같이 리턴하게 수정
=> 상태 코드 수정 및 홈 화면 api - 식물 종 추가

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/DTO/PatchUpdateMyPageReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
마이페이지 API 수정
- 토큰 로그인 관련 Authentication 적용
- 마이페이지 Request에 유효성 검증 적용
- 비밀번호 수정시 비밀번호 암호화 적용
=> Refactoring mypage

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Service/ArduinoService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/DTO/PatchUpdateMyPageReq.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
자동화 스케줄링 업데이트
- 조명 ON, OFF 로직 추가
마이페이지 자동화 관련 업데이트
- PatchMypageReq에서 auto 설정 여부 추가
- UserService단에서 auto 설정 변경하는 로직 추가
=> 마이페이지 자동화 관련 업데이트

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Controller/UserController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
비밀번호 암호화 시도시 암호화 기법상 복호화가 불가능한데 이 방법을 유지하려면 비밀번호 재설정 화면을 만들어야 해
비밀번호 암호화를 취소하고, 그대로 저장되도록 수정합니다.
=> 비밀번호 암호화 해제

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Controller/StatusController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Service/Port/StatusRepository.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Status/Service/StatusService.java
StatusRepository 상에서 함수로 리스트를 한 번에 생성하고자 했는데 DB 상에 생성일이 LocalDateTime으로 되어있어
Service 단에서 리스트를 재구성하는 형태로 수정합니다.
=> 특정 식물번호 - 물 준 날짜 리스트 API 수정

GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Controller/ArduinoController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Arduino/Service/ArduinoService.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/GrowingPetPlantApplication.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Plant/Controller/PlantController.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/Subscribe/Subscriber.java, GrowingPetPlant/src/main/java/Happy20/GrowingPetPlant/User/Service/UserService.java
아두이노 DB 데이터 수정
WHY?
이유를 모르겠지만 @Value로 넘겨주면 제대로 인식을 하지 못해 우선은 DB 정보를 그대로 명시해줬다.
마감 이후에 이 부분을 수정해 보안을 강화해야겠다.
식물 정보 API
- 식물 정보를 리턴해주는 API가 필요해 추가해줬다.
=> 아두이노 DB, 식물 정보 API
